# NAME: AKINWALE MERCY O
# MATRIC: 22PBF02392
# COURSE: CSC829

# Libraries

In [ ]:
import numpy as np
np.random.seed(123)

# Helper Functions

In [ ]:
def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    z -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """
    s = 1 / (1 + np.exp(-z))
    return s

def softmax(values):
    exp_values = np.exp(values)
    return exp_values / exp_values.sum()


def initialize_parameters(x, h, y):
    """
    Argument:
    x -- size of the input layer
    h -- size of the hidden layer
    y -- size of the output layer

    Returns:
    params -- python dictionary containing your parameters:
                    W_hidden -- weight matrix of shape (h, x)
                    b_hidden -- bias vector of shape (h, 1)
                    W_output -- weight matrix of shape (y, h)
                    b_output -- bias vector of shape (y, 1)
    """

    W1 = np.random.randn(h, x)
    b1 = np.zeros((h, 1))
    W2 = np.random.randn(y, h)
    b2 = np.zeros((y, 1))

    parameters = {"W_hidden": W1,
                  "b_hidden": b1,
                  "W_output": W2,
                  "b_output": b2}

    return parameters


def forward_propagation(X, parameters):
    """
    Argument:
    X -- input data of size (n_x, m)
    parameters -- python dictionary containing your parameters (output of initialization function)

    Returns:
    A2 -- The sigmoid output of the second activation
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2"
    """

    W1 = parameters['W_hidden']
    b1 = parameters['b_hidden']
    W2 = parameters['W_output']
    b2 = parameters['b_output']


    Z1 = np.dot(W1,X) + b1
    A1 = sigmoid(Z1)


    Z2 = np.dot(W2,A1) + b2
    A2 = softmax(Z2)

    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}

    return A2 #, cache

In [ ]:
# test
sigmoid(0)

0.5

# Implementation

In [ ]:
# Input features
X  = np.array([[1, 22, 569, 35, 0],
                [1, 7, 351, 75, 1],
                [1, 45, 451, 542, 1],
                [1, 5, 572, 8, 0],
                [0, 22, 565, 44, 1],
                [0, 24, 243, 546, 1],
                [1, 78, 953, 42, 0],])
X.shape

(7, 5)

In [ ]:
# Randomise weights and bias of the model
x, h, y = 5, 4, 3
parameters = initialize_parameters(x, h, y)

print("W1 = " + str(parameters["W_hidden"]))
print("b1 = " + str(parameters["b_hidden"]))
print("W2 = " + str(parameters["W_output"]))
print("b2 = " + str(parameters["b_output"]))


W1 = [[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
 [ 1.65143654 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]
 [-0.67888615 -0.09470897  1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609  1.0040539   0.3861864 ]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[ 0.73736858  1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052  -1.4286807 ]
 [-0.14006872 -0.8617549  -0.25561937 -2.79858911]]
b2 = [[0.]
 [0.]
 [0.]]


In [ ]:
for row in X:
    inputs_to_nn = row.reshape(-1, 1)
    output = forward_propagation(inputs_to_nn, parameters)
    print(output)
    print()

[[0.92663397]
 [0.05907092]
 [0.01429511]]

[[0.66498296]
 [0.310353  ]
 [0.02466403]]

[[0.94419578]
 [0.05247198]
 [0.00333223]]

[[0.92663397]
 [0.05907092]
 [0.01429511]]

[[0.92663397]
 [0.05907092]
 [0.01429511]]

[[0.9441976 ]
 [0.05247021]
 [0.0033322 ]]

[[0.92663397]
 [0.05907092]
 [0.01429511]]



<ipython-input-3-c83d6a8f8dfa>:11: RuntimeWarning: overflow encountered in exp
  s = 1 / (1 + np.exp(-z))
